add a host network test

diff --git a/k8s-iperf b/k8s-iperf
--- a/k8s-iperf
+++ b/k8s-iperf
@@ -17,44 +17,57 @@ if [[ ! $(kubectl get node -o name | grep "node/${SERVER_NODE}") ]]; then
     exit 1
 fi
 
-echo "[Start] iperf server"
-if [[ ! $(kubectl get pods -l app=iperf-server 2> /dev/null) ]]; then
-    cat ${DIR}/k8s-iperf.yaml | sed -s "s/{NODE}/${SERVER_NODE}/g" | kubectl apply -f -
-elif [[ $(kubectl get pod -l app=iperf-server -o jsonpath='{.items[0].metadata.labels.node}') != "${SERVER_NODE}" ]]; then
-    >&2 echo "[Error] Another server had been launched."
-    >&2 echo "$(kubectl get pods -l app=iperf-server -o wide)"
-    exit 1
-fi
+start() {
+  local scope=${1}
+  local suffix=${1:-"pod"}
+  if [ -n "$suffix" ]; then  # 检查参数是否不为空
+      suffix="-${suffix}"
+  fi
 
-until $(kubectl get pods -l app=iperf-server -o jsonpath='{.items[0].status.containerStatuses[0].ready}'); do
-    echo "Waiting for iperf server to start..."
-    sleep 5
-done
-echo
+  echo "[Start(${scope})] iperf server"
+  if [[ ! $(kubectl get pods -l app=iperf-server 2> /dev/null) ]]; then
+      cat ${DIR}/k8s-iperf${suffix}.yaml | sed -s "s/{NODE}/${SERVER_NODE}/g" | kubectl apply -f -
+  elif [[ $(kubectl get pod -l app=iperf-server -o jsonpath='{.items[0].metadata.labels.node}') != "${SERVER_NODE}" ]]; then
+      >&2 echo "[Error(${scope})] Another server had been launched."
+      >&2 echo "$(kubectl get pods -l app=iperf-server -o wide)"
+      exit 1
+  fi
 
-echo "[Start] iperf clients" 
-CLIENTS=$(kubectl get pods -l app=iperf-client -o name | cut -d'/' -f2)
-for POD in ${CLIENTS}; do
-    until $(kubectl get pod ${POD} -o jsonpath='{.status.containerStatuses[0].ready}'); do
-        echo "Waiting for ${POD} to start..."
-        sleep 5
-    done
-done
+  until $(kubectl get pods -l app=iperf-server -o jsonpath='{.items[0].status.containerStatuses[0].ready}'); do
+      echo "Waiting for iperf server to start..."
+      sleep 5
+  done
+  echo
 
-for POD in ${CLIENTS}; do
-    echo "[Run] iperf-client pod ${POD}"
-    kubectl exec ${POD} -- iperf -c iperf-server $@ &> /dev/null &
-done
+  echo "[Start(${scope})] iperf clients"
+  CLIENTS=$(kubectl get pods -l app=iperf-client -o name | cut -d'/' -f2)
+  for POD in ${CLIENTS}; do
+      until $(kubectl get pod ${POD} -o jsonpath='{.status.containerStatuses[0].ready}'); do
+          echo "Waiting for ${POD} to start..."
+          sleep 5
+      done
+  done
 
-until [[ $(jobs | grep -v Running) != "" ]]; do
-    printf "."
-    sleep 2
-done
-printf " done\n"
+  SERVER_NODE_ADDRESS=$(kubectl get nodes ${SERVER_NODE} -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')
+  for POD in ${CLIENTS}; do
+      echo "[Run(${scope})] iperf-client pod ${POD}"
+      if [[ "$scope" = "pod" ]]; then
+          kubectl exec ${POD} -- iperf -c iperf-server $@ &> /dev/null
+      fi
+      if [[ "$scope" = "host" ]]; then
+          kubectl exec ${POD} -- iperf -c ${SERVER_NODE_ADDRESS} $@ &> /dev/null
+      fi
+  done
 
-echo
-kubectl logs -l app=iperf-server 
-echo
+  printf " done\n"
 
-echo "[Cleanup]"
-kubectl delete --cascade -f ${DIR}/k8s-iperf.yaml
+  echo
+  kubectl logs -l app=iperf-server
+  echo
+
+  echo "[Cleanup(${scope})]"
+  kubectl delete --cascade -f ${DIR}/k8s-iperf${suffix}.yaml
+}
+
+start "pod"
+start "host"
